env:
  - OS_TYPE=centos OS_VERSION=7

install:
  - wget https://www.mpfr.org/mpfr-4.0.1/mpfr-4.0.1.zip
  - unzip mpfr-4.0.1.zip
  - cd mpfr-4.0.1
  - ./configure
  - make
  - make check
  - make install
language: python
compiler:
  - gcc
python:
  - "3.6"
sudo: required
script: 
  - py.test
