sudo: required
language: generic

cache:
  directories:
    - $HOME/.ccache
notifications:
  slack:
    on_success: never
    on_failure : never

matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: 2.7

    - os: linux
      dist: xenial
      language: python
      python: 3.5

    - os: linux
      dist: xenial
      language: python
      python: 3.6

install:
  - |
    export PATH="/usr/lib/ccache:$PATH"
    ccache -M 256M && ccache -s
    sudo apt-get install libgmp-dev libmpfr-dev libmpfi-dev libmpc-dev texlive texlive-latex-extra latexmk
    pip install Cython --verbose --disable-pip-version-check
    python setup.py sdist
    pip install dist/gmpy2-*.tar.gz
    cat requirements.txt | xargs -n 1 pip install
    pip install pytest pytest-cov coverage
    pip install sphinx
before script:
  - export PYTHONPATH=$PYTHONPATH:$HOME
script:
  - coverage run --source=./ -m unittest discover -s ./ -p '*_test.py'

after script:
  - codecov
